import {
  User,
  Patient,
  XRayAnalysis,
  SymptomAssessment,
  CoughAnalysis,
  LabResult,
  TreatmentPlan,
  TimelineEvent,
  NotificationItem,
  Clinic,
  AuditLog,
  AnalyticsSummary,
} from '../types';
import { REAL_UZBEKISTAN_CLINICS } from './uzbekistanClinicsData';

export const mockUsers: User[] = [
  {
    id: 'usr_doc_0',
    name: 'Sharipova Dinora',
    firstName: 'Dinora',
    lastName: 'Sharipova',
    email: '2007sharipova@gmail.com',
    role: 'DOCTOR',
    clinicId: 'cln_uz_rifp',
    clinicName: 'Respublika Ixtisoslashtirilgan Ftiziatriya va Pulmonologiya Markazi (RIFP IATM)',
    specialty: 'Lead Pulmonology Specialist',
    position: 'Bosh ftiziatr-pulmonolog / Lead Pulmonologist',
    department: "Ftiziatriya va Pulmonologiya Bo'limi",
    phone: '+998 90 987 6543',
    telegram: '@javaa_backend',
    bio: "O'zbekistonda sil kasalligini erta aniqlash va sun'iy intellekt asosida multimodal diagnostika bo'yicha mas'ul mutaxassis.",
    region: 'Toshkent shahri',
    licenseNumber: 'MD-UZ-77201',
    active: true,
    createdAt: '2025-01-01T08:00:00Z',
    lastLogin: '2026-08-20T06:15:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813593-c418c322b270?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'usr_doc_1',
    name: 'Dr. Sarah Chen, MD',
    email: 'sarah.chen@tbdetect.ai',
    role: 'DOCTOR',
    clinicId: 'cln_central_1',
    clinicName: 'Central Pulmonary & Thoracic Institute',
    specialty: 'Senior Pulmonologist & TB Specialist',
    phone: '+998 71 200 4501',
    licenseNumber: 'MD-UZ-84920',
    active: true,
    createdAt: '2025-01-15T08:00:00Z',
    lastLogin: '2026-08-20T05:30:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'usr_doc_2',
    name: 'Dr. Alisher Navoi, PhD',
    email: 'alisher.navoi@tbdetect.ai',
    role: 'DOCTOR',
    clinicId: 'cln_central_1',
    clinicName: 'Central Pulmonary & Thoracic Institute',
    specialty: 'Consultant Thoracic Radiologist',
    phone: '+998 71 200 4502',
    licenseNumber: 'MD-UZ-91044',
    active: true,
    createdAt: '2025-02-01T09:00:00Z',
    lastLogin: '2026-08-19T14:15:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'usr_admin_1',
    name: 'Bekzod Tulyaganov',
    email: 'admin.bekzod@tbdetect.ai',
    role: 'CLINIC_ADMIN',
    clinicId: 'cln_central_1',
    clinicName: 'Central Pulmonary & Thoracic Institute',
    phone: '+998 90 123 4567',
    active: true,
    createdAt: '2024-11-10T10:00:00Z',
    lastLogin: '2026-08-20T04:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'usr_sysadmin_1',
    name: 'Sharipova Dinora',
    firstName: 'Dinora',
    lastName: 'Sharipova',
    email: '2007sharipova@gmail.com',
    role: 'ADMIN',
    clinicId: 'cln_uz_rifp',
    clinicName: 'Respublika Ixtisoslashtirilgan Ftiziatriya va Pulmonologiya Markazi (RIFP IATM)',
    specialty: 'Lead Pulmonology Specialist & AI Architect',
    position: 'Lead Pulmonology Specialist & AI Architect',
    department: 'Markaziy Konsilium va Tizim Boshqaruvi',
    telegram: '@javaa_backend',
    phone: '+998 90 987 6543',
    region: 'Toshkent, O‘zbekiston',
    bio: 'TBDetect AI Milliy platformasi bosh administratori va yetakchi ftiziatr-mutaxassisi.',
    active: true,
    createdAt: '2024-09-01T08:00:00Z',
    lastLogin: '2026-08-20T06:00:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813593-c418c322b270?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'usr_staff_1',
    name: 'Elena Smirnova, RN',
    email: 'elena.staff@tbdetect.ai',
    role: 'MEDICAL_STAFF',
    clinicId: 'cln_uz_rifp',
    clinicName: 'Respublika Ixtisoslashtirilgan Ftiziatriya va Pulmonologiya Markazi (RIFP IATM)',
    phone: '+998 97 450 1122',
    active: true,
    createdAt: '2025-03-12T08:30:00Z',
    lastLogin: '2026-08-20T05:10:00Z',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813593-55d7f191f692?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'usr_patient_1',
    name: 'Rustam Karimov',
    email: 'rustam.karimov@example.uz',
    role: 'PATIENT',
    clinicId: 'cln_uz_rifp',
    clinicName: 'Respublika Ixtisoslashtirilgan Ftiziatriya va Pulmonologiya Markazi (RIFP IATM)',
    phone: '+998 90 912 3456',
    active: true,
    createdAt: '2026-07-10T11:00:00Z',
    lastLogin: '2026-08-18T19:00:00Z',
  },
];

export const mockClinics: Clinic[] = [...REAL_UZBEKISTAN_CLINICS];

export const mockPatients: Patient[] = [
  {
    id: 'pat_001',
    nationalId: 'TB-2026-089',
    firstName: 'Rustam',
    lastName: 'Karimov',
    dateOfBirth: '1978-04-12',
    age: 48,
    gender: 'MALE',
    phone: '+998 90 912 3456',
    email: 'rustam.karimov@example.uz',
    address: 'Chilanzar-9, Apt 44, Tashkent',
    region: 'Tashkent City',
    riskScore: 84,
    riskLevel: 'HIGH',
    status: 'PENDING_REVIEW',
    treatmentStatus: 'ACTIVE',
    assignedDoctorId: 'usr_doc_1',
    assignedDoctorName: 'Dr. Sarah Chen, MD',
    clinicId: 'cln_central_1',
    clinicName: 'Central Pulmonary & Thoracic Institute',
    tbHistory: 'HOUSEHOLD_CONTACT',
    comorbidities: ['Diabetes Mellitus Type 2', 'Former Smoker (20 pack-years)'],
    emergencyContact: {
      name: 'Nargiza Karimova',
      relationship: 'Spouse',
      phone: '+998 90 912 3457',
    },
    occupation: 'Construction Site Supervisor',
    notes: 'Persistent 4-week productive cough with nocturnal fever spikes. Household contact with brother diagnosed with active pulmonary TB 6 months ago.',
    createdAt: '2026-07-10T09:30:00Z',
    updatedAt: '2026-08-19T16:20:00Z',
    lastScreeningDate: '2026-08-19',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'pat_002',
    nationalId: 'TB-2026-104',
    firstName: 'Nodira',
    lastName: 'Aliyeva',
    dateOfBirth: '1992-09-24',
    age: 34,
    gender: 'FEMALE',
    phone: '+998 93 401 2288',
    email: 'nodira.aliyeva@example.uz',
    address: 'Amir Temur Street 19, Samarkand',
    region: 'Samarkand Region',
    riskScore: 48,
    riskLevel: 'MODERATE',
    status: 'PENDING_REVIEW',
    treatmentStatus: 'NOT_STARTED',
    assignedDoctorId: 'usr_doc_2',
    assignedDoctorName: 'Dr. Alisher Navoi, PhD',
    clinicId: 'cln_central_1',
    clinicName: 'Central Pulmonary & Thoracic Institute',
    tbHistory: 'NONE',
    comorbidities: ['Mild Bronchial Asthma'],
    emergencyContact: {
      name: 'Anvar Aliyev',
      relationship: 'Brother',
      phone: '+998 93 401 9900',
    },
    occupation: 'Primary School Teacher',
    notes: 'Subacute dry cough for 3 weeks, mild fatigue. No hemoptysis reported. Sputum GeneXpert ordered.',
    createdAt: '2026-08-05T14:10:00Z',
    updatedAt: '2026-08-18T11:00:00Z',
    lastScreeningDate: '2026-08-18',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'pat_003',
    nationalId: 'TB-2026-118',
    firstName: 'Bekhzod',
    lastName: 'Tursunov',
    dateOfBirth: '1964-11-03',
    age: 62,
    gender: 'MALE',
    phone: '+998 97 733 9011',
    email: 'bekhzod.tursunov@example.uz',
    address: 'Navoi Prospect 52, Bukhara',
    region: 'Bukhara Region',
    riskScore: 92,
    riskLevel: 'CRITICAL',
    status: 'FOLLOW_UP_REQUIRED',
    treatmentStatus: 'ACTIVE',
    assignedDoctorId: 'usr_doc_1',
    assignedDoctorName: 'Dr. Sarah Chen, MD',
    clinicId: 'cln_central_1',
    clinicName: 'Central Pulmonary & Thoracic Institute',
    tbHistory: 'PREVIOUS_CURED',
    comorbidities: ['Hypertension', 'Severe Chronic Bronchitis', 'Immunocompromised'],
    emergencyContact: {
      name: 'Gulchehra Tursunova',
      relationship: 'Daughter',
      phone: '+998 97 733 9012',
    },
    occupation: 'Retired Textile Worker',
    notes: 'Severe hemoptysis episode 2 days ago, significant weight loss (-7.5 kg in 2 months). Previous TB episode treated in 2018.',
    createdAt: '2026-07-28T08:00:00Z',
    updatedAt: '2026-08-20T02:45:00Z',
    lastScreeningDate: '2026-08-20',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'pat_004',
    nationalId: 'TB-2026-135',
    firstName: 'Malika',
    lastName: 'Yusupova',
    dateOfBirth: '1999-02-18',
    age: 27,
    gender: 'FEMALE',
    phone: '+998 91 555 4321',
    email: 'malika.yusupova@example.uz',
    address: 'Buyuk Ipak Yoli 104, Tashkent',
    region: 'Tashkent City',
    riskScore: 14,
    riskLevel: 'LOW',
    status: 'REVIEWED',
    treatmentStatus: 'NOT_STARTED',
    assignedDoctorId: 'usr_doc_2',
    assignedDoctorName: 'Dr. Alisher Navoi, PhD',
    clinicId: 'cln_central_1',
    clinicName: 'Central Pulmonary & Thoracic Institute',
    tbHistory: 'NONE',
    comorbidities: [],
    emergencyContact: {
      name: 'Timur Yusupov',
      relationship: 'Spouse',
      phone: '+998 91 555 4322',
    },
    occupation: 'Graphic Designer',
    notes: 'Routine health checkup following seasonal viral influenza. Clear lung fields on radiograph.',
    createdAt: '2026-08-12T10:15:00Z',
    updatedAt: '2026-08-16T15:30:00Z',
    lastScreeningDate: '2026-08-16',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'pat_005',
    nationalId: 'TB-2026-142',
    firstName: 'Jasur',
    lastName: 'Saidov',
    dateOfBirth: '1975-06-30',
    age: 51,
    gender: 'MALE',
    phone: '+998 90 333 7788',
    email: 'jasur.saidov@example.uz',
    address: 'Mustaqillik Street 12, Fergana',
    region: 'Fergana Region',
    riskScore: 76,
    riskLevel: 'HIGH',
    status: 'PENDING_REVIEW',
    treatmentStatus: 'ACTIVE',
    assignedDoctorId: 'usr_doc_1',
    assignedDoctorName: 'Dr. Sarah Chen, MD',
    clinicId: 'cln_fergana_3',
    clinicName: 'Fergana Valley Primary Screening Hub',
    tbHistory: 'KNOWN_EXPOSURE',
    comorbidities: ['Heavy Smoker (30 pack-years)', 'Chronic Cough'],
    emergencyContact: {
      name: 'Munira Saidova',
      relationship: 'Spouse',
      phone: '+998 90 333 7789',
    },
    occupation: 'Long-haul Freight Driver',
    notes: 'Severe night sweats and chest pain during respiration. Positive sputum smear AFB 2+.',
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-08-17T14:00:00Z',
    lastScreeningDate: '2026-08-17',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'pat_006',
    nationalId: 'TB-2026-150',
    firstName: 'Elena',
    lastName: 'Kim',
    dateOfBirth: '1987-12-14',
    age: 39,
    gender: 'FEMALE',
    phone: '+998 97 123 4455',
    email: 'elena.kim@example.uz',
    address: 'Mirabad District, Block 4, Tashkent',
    region: 'Tashkent City',
    riskScore: 22,
    riskLevel: 'LOW',
    status: 'DISCHARGED',
    treatmentStatus: 'NOT_STARTED',
    assignedDoctorId: 'usr_doc_2',
    assignedDoctorName: 'Dr. Alisher Navoi, PhD',
    clinicId: 'cln_central_1',
    clinicName: 'Central Pulmonary & Thoracic Institute',
    tbHistory: 'NONE',
    comorbidities: ['Seasonal Allergic Rhinitis'],
    emergencyContact: {
      name: 'Dmitriy Kim',
      relationship: 'Spouse',
      phone: '+998 97 123 4456',
    },
    occupation: 'Accountant',
    notes: 'Annual pre-employment screening completed. Negative chest X-ray and normal inflammatory markers.',
    createdAt: '2026-08-10T16:00:00Z',
    updatedAt: '2026-08-15T09:00:00Z',
    lastScreeningDate: '2026-08-15',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'pat_007',
    nationalId: 'TB-2026-161',
    firstName: 'Sherzod',
    lastName: 'Rakhimov',
    dateOfBirth: '1981-08-05',
    age: 45,
    gender: 'MALE',
    phone: '+998 94 660 1199',
    email: 'sherzod.rakhimov@example.uz',
    address: 'Gagarin Street 77, Termez',
    region: 'Surkhandarya Region',
    riskScore: 68,
    riskLevel: 'HIGH',
    status: 'FOLLOW_UP_REQUIRED',
    treatmentStatus: 'ACTIVE',
    assignedDoctorId: 'usr_doc_1',
    assignedDoctorName: 'Dr. Sarah Chen, MD',
    clinicId: 'cln_mobile_4',
    clinicName: 'Mobile Radiology Screening Unit #04',
    tbHistory: 'HOUSEHOLD_CONTACT',
    comorbidities: ['Hypertension Stage 1'],
    emergencyContact: {
      name: 'Shakhnoza Rakhimova',
      relationship: 'Spouse',
      phone: '+998 94 660 1198',
    },
    occupation: 'Agricultural Farmer',
    notes: 'Mobile unit screening identified right apical consolidation. Started on 2HRZE standard 6-month regimen, 96.5% DOTS adherence rate.',
    createdAt: '2026-06-15T11:20:00Z',
    updatedAt: '2026-08-19T08:30:00Z',
    lastScreeningDate: '2026-08-19',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=256&q=80',
  },
  {
    id: 'pat_008',
    nationalId: 'TB-2026-177',
    firstName: 'Dilnoza',
    lastName: 'Usmanova',
    dateOfBirth: '1995-03-19',
    age: 31,
    gender: 'FEMALE',
    phone: '+998 90 882 3344',
    email: 'dilnoza.usmanova@example.uz',
    address: 'Uchtepa District, 26-Quarter, Tashkent',
    region: 'Tashkent City',
    riskScore: 56,
    riskLevel: 'MODERATE',
    status: 'PENDING_REVIEW',
    treatmentStatus: 'NOT_STARTED',
    assignedDoctorId: 'usr_doc_2',
    assignedDoctorName: 'Dr. Alisher Navoi, PhD',
    clinicId: 'cln_central_1',
    clinicName: 'Central Pulmonary & Thoracic Institute',
    tbHistory: 'KNOWN_EXPOSURE',
    comorbidities: ['Anemia (Hb 10.2 g/dL)'],
    emergencyContact: {
      name: 'Farrukh Usmanov',
      relationship: 'Brother',
      phone: '+998 90 882 3345',
    },
    occupation: 'Pharmacist',
    notes: 'Workplace exposure to diagnosed patient. Presenting with low-grade evening fevers and chronic dry cough.',
    createdAt: '2026-08-14T13:00:00Z',
    updatedAt: '2026-08-19T17:45:00Z',
    lastScreeningDate: '2026-08-19',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=256&q=80',
  },
];

export const mockXRays: XRayAnalysis[] = [
  {
    id: 'xray_001',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=300&q=80',
    uploadedAt: '2026-08-19T14:30:00Z',
    uploadedBy: 'Elena Smirnova, RN',
    analyzedAt: '2026-08-19T14:30:12Z',
    status: 'COMPLETED',
    riskScore: 84,
    riskLevel: 'HIGH',
    confidence: 0.94,
    findings: [
      {
        zone: 'UPPER_RIGHT_LOBE',
        description: 'Dense heterogeneous consolidation with suspected thick-walled cavitary lesion (~2.4 cm).',
        confidence: 0.96,
        boundingPoly: { x: 55, y: 18, width: 30, height: 28 },
      },
      {
        zone: 'BILATERAL_APICAL',
        description: 'Apical pleural thickening and fibro-productive streaky opacities.',
        confidence: 0.88,
        boundingPoly: { x: 20, y: 15, width: 62, height: 18 },
      },
      {
        zone: 'HILAR_LYMPHADENOPATHY',
        description: 'Prominent right hilar lymph node enlargement without severe vascular congestion.',
        confidence: 0.82,
        boundingPoly: { x: 48, y: 42, width: 16, height: 20 },
      },
    ],
    impression: 'High radiographic suspicion of active pulmonary tuberculosis characterized by right upper lobe cavitation, apical infiltrative changes, and prominent hilar involvement.',
    heatmapCoordinates: [
      { x: 68, y: 28, radius: 45, intensity: 0.95 },
      { x: 32, y: 24, radius: 30, intensity: 0.65 },
      { x: 54, y: 48, radius: 28, intensity: 0.72 },
    ],
    dicomMetadata: {
      viewPosition: 'PA (Posteroanterior)',
      kvp: '120 kVp',
      exposureTime: '12 ms',
      manufacturer: 'Siemens Healthineers Multix Impact',
    },
    doctorReview: {
      reviewedBy: 'usr_doc_1',
      doctorName: 'Dr. Sarah Chen, MD',
      reviewedAt: '2026-08-19T16:10:00Z',
      clinicalDecision: 'CONFIRMED_SUSPICION',
      notes: 'Confirmed high radiologic probability of active cavitary TB. Correlates with persistent night sweats. Expedite GeneXpert MTB/RIF and initiate DOTS therapy protocol immediately.',
      signed: true,
    },
  },
  {
    id: 'xray_002',
    patientId: 'pat_002',
    patientName: 'Nodira Aliyeva',
    imageUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=300&q=80',
    uploadedAt: '2026-08-18T10:15:00Z',
    uploadedBy: 'Elena Smirnova, RN',
    analyzedAt: '2026-08-18T10:15:10Z',
    status: 'COMPLETED',
    riskScore: 48,
    riskLevel: 'MODERATE',
    confidence: 0.86,
    findings: [
      {
        zone: 'UPPER_LEFT_LOBE',
        description: 'Ill-defined patchy subsegmental opacity in left mid-to-upper lung zone.',
        confidence: 0.79,
        boundingPoly: { x: 22, y: 32, width: 24, height: 26 },
      },
    ],
    impression: 'Indeterminate patchy infiltration in the left mid-zone. Differential includes early atypical pneumonia vs early tuberculosis infiltration.',
    heatmapCoordinates: [
      { x: 34, y: 44, radius: 36, intensity: 0.74 },
    ],
    dicomMetadata: {
      viewPosition: 'PA (Posteroanterior)',
      kvp: '115 kVp',
      exposureTime: '10 ms',
      manufacturer: 'GE Optima XR646 HD',
    },
  },
  {
    id: 'xray_003',
    patientId: 'pat_003',
    patientName: 'Bekhzod Tursunov',
    imageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=300&q=80',
    uploadedAt: '2026-08-20T02:30:00Z',
    uploadedBy: 'Elena Smirnova, RN',
    analyzedAt: '2026-08-20T02:30:14Z',
    status: 'COMPLETED',
    riskScore: 92,
    riskLevel: 'CRITICAL',
    confidence: 0.98,
    findings: [
      {
        zone: 'BILATERAL_APICAL',
        description: 'Extensive bilateral apical destruction with multiple communicating cavitary complexes.',
        confidence: 0.99,
        boundingPoly: { x: 18, y: 12, width: 66, height: 35 },
      },
      {
        zone: 'LOWER_RIGHT_LOBE',
        description: 'Secondary bronchogenic tree-in-bud dissemination into lower lung fields.',
        confidence: 0.91,
        boundingPoly: { x: 58, y: 55, width: 28, height: 28 },
      },
    ],
    impression: 'Critical radiologic manifestation of advanced bilateral cavitary tuberculosis with endobronchial dissemination and volume loss.',
    heatmapCoordinates: [
      { x: 70, y: 22, radius: 52, intensity: 0.99 },
      { x: 28, y: 20, radius: 48, intensity: 0.95 },
      { x: 68, y: 64, radius: 38, intensity: 0.85 },
    ],
    dicomMetadata: {
      viewPosition: 'AP (Portable Semi-erect)',
      kvp: '125 kVp',
      exposureTime: '15 ms',
      manufacturer: 'Philips DigitalDiagnost C90',
    },
  },
  {
    id: 'xray_004',
    patientId: 'pat_004',
    patientName: 'Malika Yusupova',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=300&q=80',
    uploadedAt: '2026-08-16T15:00:00Z',
    uploadedBy: 'Elena Smirnova, RN',
    analyzedAt: '2026-08-16T15:00:08Z',
    status: 'COMPLETED',
    riskScore: 14,
    riskLevel: 'LOW',
    confidence: 0.97,
    findings: [],
    impression: 'Clear lung parenchyma without focal consolidation, cavitation, or pleural effusion. Normal cardiothoracic ratio.',
    heatmapCoordinates: [],
    dicomMetadata: {
      viewPosition: 'PA (Posteroanterior)',
      kvp: '110 kVp',
      exposureTime: '8 ms',
      manufacturer: 'Siemens Multix Impact',
    },
    doctorReview: {
      reviewedBy: 'usr_doc_2',
      doctorName: 'Dr. Alisher Navoi, PhD',
      reviewedAt: '2026-08-16T15:25:00Z',
      clinicalDecision: 'NEGATIVE',
      notes: 'Normal chest radiograph. No evidence of active or latent pulmonary tuberculosis.',
      signed: true,
    },
  },
];

export const mockSymptomAssessments: SymptomAssessment[] = [
  {
    id: 'sym_001',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    assessedAt: '2026-08-19T13:45:00Z',
    assessedBy: 'Dr. Sarah Chen, MD',
    symptoms: {
      coughDurationDays: 28,
      hasHemoptysis: true,
      hasFever: true,
      feverDurationDays: 18,
      hasNightSweats: true,
      hasWeightLoss: true,
      weightLossKg: 5.2,
      hasChestPain: true,
      hasFatigue: true,
      hasLossOfAppetite: true,
      hasShortnessOfBreath: true,
    },
    riskFactors: {
      closeContactWithTB: true,
      smoker: true,
      diabetic: true,
      immunocompromised: false,
      livingInCrowdedArea: false,
    },
    calculatedRiskScore: 88,
    riskLevel: 'HIGH',
    summary: 'Classic presentation of constitutional TB symptoms: >3 weeks productive cough with hemoptysis streaks, drenching night sweats, 5.2kg weight loss, and household contact.',
  },
  {
    id: 'sym_002',
    patientId: 'pat_002',
    patientName: 'Nodira Aliyeva',
    assessedAt: '2026-08-18T09:30:00Z',
    assessedBy: 'Dr. Alisher Navoi, PhD',
    symptoms: {
      coughDurationDays: 21,
      hasHemoptysis: false,
      hasFever: true,
      feverDurationDays: 7,
      hasNightSweats: false,
      hasWeightLoss: false,
      hasChestPain: false,
      hasFatigue: true,
      hasLossOfAppetite: false,
      hasShortnessOfBreath: false,
    },
    riskFactors: {
      closeContactWithTB: false,
      smoker: false,
      diabetic: false,
      immunocompromised: false,
      livingInCrowdedArea: true,
    },
    calculatedRiskScore: 45,
    riskLevel: 'MODERATE',
    summary: 'Subacute dry cough for 3 weeks with evening subfebrile temperatures. Moderate probability requiring microbiological confirmation.',
  },
];

export const mockCoughAnalyses: CoughAnalysis[] = [
  {
    id: 'cgh_001',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    recordedAt: '2026-08-19T14:10:00Z',
    durationSeconds: 6.8,
    audioWaveformData: [12, 18, 45, 88, 95, 76, 32, 15, 22, 65, 92, 85, 42, 18, 9, 28, 77, 98, 64, 20, 8, 14, 40, 82, 60, 25, 10],
    explosivePhaseDurationMs: 142,
    energySpectralDensity: 0.88,
    tbAcousticScore: 81,
    riskLevel: 'HIGH',
    confidence: 0.91,
    interpretation: 'Acoustic feature signature demonstrates prolonged explosive phase duration (>130ms), wet crackle harmonics, and abnormal high-frequency spectral clustering consistent with bronchial fluid accumulation.',
  },
  {
    id: 'cgh_002',
    patientId: 'pat_002',
    patientName: 'Nodira Aliyeva',
    recordedAt: '2026-08-18T10:00:00Z',
    durationSeconds: 5.4,
    audioWaveformData: [8, 14, 30, 52, 64, 48, 20, 10, 15, 45, 60, 50, 22, 8, 12, 38, 55, 42, 15, 6],
    explosivePhaseDurationMs: 88,
    energySpectralDensity: 0.44,
    tbAcousticScore: 42,
    riskLevel: 'MODERATE',
    confidence: 0.83,
    interpretation: 'Dry acoustic pattern with standard explosive phase dynamics. Slight elevation in upper harmonic ratio; recommended for secondary screening check.',
  },
];

export const mockLabResults: LabResult[] = [
  {
    id: 'lab_001',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    testType: 'GENEXPERT_MTB',
    testName: 'GeneXpert MTB/RIF Ultra Molecular Assay',
    performedDate: '2026-08-19',
    reportedDate: '2026-08-19',
    laboratoryName: 'Central Reference TB Lab Tashkent',
    technicianName: 'Dr. Mansur Zokirov, Pathologist',
    result: 'MTB DETECTED (HIGH LOAD); RIFAMPICIN RESISTANCE NOT DETECTED',
    isAbnormal: true,
    quantitativeValue: 4.8,
    units: 'log10 CFU/mL equivalent',
    referenceRange: 'MTB Not Detected',
    status: 'FLAGGED',
    notes: 'Real-time PCR confirmed Mycobacterium tuberculosis complex DNA with high bacterial load. Wild-type rpoB gene (Rifampicin susceptible).',
    documentUrl: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?w=800&auto=format&fit=crop&q=60',
    documentName: 'GeneXpert_Ultra_Report_pat001.pdf',
    documentSize: '1.4 MB',
    documentMimeType: 'application/pdf',
    isDemoSimulation: true,
  },
  {
    id: 'lab_002',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    testType: 'SPUTUM_SMEAR',
    testName: 'Ziehl-Neelsen Acid-Fast Bacilli (AFB) Smear Microscopy',
    performedDate: '2026-08-19',
    reportedDate: '2026-08-19',
    laboratoryName: 'Central Reference TB Lab Tashkent',
    technicianName: 'Dr. Mansur Zokirov, Pathologist',
    result: 'POSITIVE 3+ (AFB > 10 per oil immersion field)',
    isAbnormal: true,
    referenceRange: 'Negative / No AFB in 100 fields',
    status: 'COMPLETED',
    notes: 'High infectious potential. Recommend strict respiratory isolation and contact tracing.',
    documentUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&auto=format&fit=crop&q=60',
    documentName: 'AFB_Microscopy_Scan_pat001.png',
    documentSize: '2.1 MB',
    documentMimeType: 'image/png',
    isDemoSimulation: true,
  },
  {
    id: 'lab_003',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    testType: 'CRP',
    testName: 'C-Reactive Protein (High Sensitivity)',
    performedDate: '2026-08-19',
    reportedDate: '2026-08-19',
    laboratoryName: 'Central Reference TB Lab Tashkent',
    technicianName: 'N. Karimova, Lab Specialist',
    result: '48.6 mg/L (Significantly Elevated)',
    isAbnormal: true,
    referenceRange: '< 5.0 mg/L',
    units: 'mg/L',
    quantitativeValue: 48.6,
    status: 'COMPLETED',
    notes: 'Acute systemic inflammatory response. Monitor with treatment progression.',
    documentName: 'Biochemistry_Panel_CRP.pdf',
    documentSize: '620 KB',
    documentMimeType: 'application/pdf',
    isDemoSimulation: true,
  },
  {
    id: 'lab_004',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    testType: 'ESR',
    testName: 'Erythrocyte Sedimentation Rate (Westergren)',
    performedDate: '2026-08-19',
    reportedDate: '2026-08-19',
    laboratoryName: 'Central Reference TB Lab Tashkent',
    technicianName: 'N. Karimova, Lab Specialist',
    result: '62 mm/hr (Elevated)',
    isAbnormal: true,
    referenceRange: '0 - 15 mm/hr',
    units: 'mm/hr',
    quantitativeValue: 62,
    status: 'COMPLETED',
    notes: 'Elevated sedimentation rate consistent with chronic inflammatory/granulomatous process.',
    isDemoSimulation: true,
  },
  {
    id: 'lab_005',
    patientId: 'pat_002',
    patientName: 'Nodira Aliyeva',
    testType: 'SPUTUM_SMEAR',
    testName: 'Ziehl-Neelsen Acid-Fast Bacilli (AFB) Smear Microscopy',
    performedDate: '2026-08-18',
    reportedDate: '2026-08-18',
    laboratoryName: 'Samarkand Regional Diagnostic Center',
    technicianName: 'A. Safarova, Lab Tech',
    result: 'NEGATIVE (No Acid-Fast Bacilli detected in 100 fields)',
    isAbnormal: false,
    referenceRange: 'Negative / No AFB in 100 fields',
    status: 'COMPLETED',
    notes: 'First sample negative. Second early morning sputum specimen submitted for GeneXpert.',
    isDemoSimulation: true,
  },
  {
    id: 'lab_006',
    patientId: 'pat_003',
    patientName: 'Bekhzod Tursunov',
    testType: 'GENEXPERT_MTB',
    testName: 'GeneXpert MTB/XDR Molecular Assay',
    performedDate: '2026-08-20',
    reportedDate: '2026-08-20',
    laboratoryName: 'National Center of Tuberculosis & Pulmonology',
    technicianName: 'Dr. K. Boboev, Senior Geneticist',
    result: 'MTB DETECTED; RIF RESISTANCE DETECTED; INH RESISTANCE DETECTED (MDR-TB)',
    isAbnormal: true,
    referenceRange: 'MTB Not Detected',
    status: 'FLAGGED',
    notes: 'Multidrug-resistant strain identified (Mutations in rpoB S531L and katG S315T). Immediate switch to BPaLM all-oral MDR regimen required.',
    documentName: 'MDR_GeneXpert_XDR_Report.pdf',
    documentSize: '1.8 MB',
    documentMimeType: 'application/pdf',
    isDemoSimulation: true,
  },
];

export const mockTreatmentPlans: TreatmentPlan[] = [
  {
    id: 'tx_001',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    regimenName: 'WHO Standard First-Line: 2HRZE / 4HR (Fixed-Dose Combination)',
    startDate: '2026-08-20',
    plannedDurationMonths: 6,
    estimatedEndDate: '2027-02-20',
    currentPhase: 'INTENSIVE_PHASE',
    status: 'ACTIVE',
    adherenceRate: 98.4,
    dosesPrescribed: 180,
    dosesTaken: 62,
    missedDoses: 1,
    facility: 'Central Reference TB Hospital Tashkent',
    supervisingDoctor: 'Dr. Sarah Chen, MD',
    notes: 'Standard 4-FDC intensive phase initiation under Directly Observed Therapy (DOTS). Baseline liver function monitored.',
    isDemoSimulation: true,
    weightLog: [
      { date: '2026-08-10', weightKg: 64.0 },
      { date: '2026-08-15', weightKg: 63.8 },
      { date: '2026-08-20', weightKg: 64.2 },
    ],
    symptomSeverityScoreLog: [
      { date: '2026-08-10', score: 8.5 },
      { date: '2026-08-15', score: 8.0 },
      { date: '2026-08-20', score: 7.2 },
    ],
    medications: [
      {
        id: 'med_001',
        name: 'Rifampicin (R) + Isoniazid (H) + Pyrazinamide (Z) + Ethambutol (E) 4-FDC',
        dosage: '150mg/75mg/400mg/275mg (4 tablets daily)',
        frequency: 'Once daily in morning (Directly Observed)',
        notes: 'Take with full glass of water. Monitor liver function enzymes (ALT/AST) every 2 weeks.',
      },
      {
        id: 'med_002',
        name: 'Pyridoxine (Vitamin B6)',
        dosage: '50 mg once daily',
        frequency: 'Daily with 4-FDC',
        notes: 'Peripheral neuropathy prophylaxis.',
      },
    ],
    doseLogs: [
      {
        id: 'dose_001',
        treatmentPlanId: 'tx_001',
        patientId: 'pat_001',
        date: '2026-08-21',
        medicationName: 'Rifampicin + Isoniazid + Pyrazinamide + Ethambutol 4-FDC',
        status: 'TAKEN',
        patientNote: 'Observed and swallowed at 08:30 AM with water.',
        doctorNote: 'Supervised by Nurse Farida at DOTS station.',
        loggedAt: '2026-08-21T08:35:00Z',
        isDemoSimulation: true,
      },
      {
        id: 'dose_002',
        treatmentPlanId: 'tx_001',
        patientId: 'pat_001',
        date: '2026-08-20',
        medicationName: 'Rifampicin + Isoniazid + Pyrazinamide + Ethambutol 4-FDC',
        status: 'TAKEN',
        patientNote: 'Swallowed without complaints.',
        doctorNote: 'First DOTS dose dispensed and verified.',
        loggedAt: '2026-08-20T09:00:00Z',
        isDemoSimulation: true,
      },
      {
        id: 'dose_003',
        treatmentPlanId: 'tx_001',
        patientId: 'pat_001',
        date: '2026-08-18',
        medicationName: 'Pyridoxine (Vitamin B6)',
        status: 'MISSED',
        patientNote: 'Patient traveling to regional clinic; dose missed.',
        doctorNote: 'Follow-up phone call completed. Re-supplied at morning appointment.',
        loggedAt: '2026-08-18T18:00:00Z',
        isDemoSimulation: true,
      },
    ],
    sideEffects: [
      {
        id: 'se_001',
        treatmentPlanId: 'tx_001',
        patientId: 'pat_001',
        symptom: 'Mild transient nausea post-ingestion',
        severity: 'MILD',
        date: '2026-08-20',
        notes: 'Occurred 30 mins after taking 4-FDC. Advised to take with light biscuit if nausea persists.',
        status: 'MONITORING',
        reportedBy: 'Patient via DOTS nurse',
        doctorActionNote: 'Advised hydration and symptom log. Re-evaluate ALT/AST if worsens.',
        isDemoSimulation: true,
      },
    ],
    nextAppointmentDate: '2026-09-03',
  },
  {
    id: 'tx_007',
    patientId: 'pat_007',
    patientName: 'Sherzod Rakhimov',
    regimenName: 'Standard 2HRZE / 4HR (Continuation Phase)',
    startDate: '2026-06-20',
    plannedDurationMonths: 6,
    estimatedEndDate: '2026-12-20',
    currentPhase: 'CONTINUATION_PHASE',
    status: 'ACTIVE',
    adherenceRate: 96.5,
    dosesPrescribed: 180,
    dosesTaken: 58,
    missedDoses: 2,
    facility: 'Regional Pulmonology Dispensary Samarkand',
    supervisingDoctor: 'Dr. Sarah Chen, MD',
    notes: 'Smooth transition from intensive to continuation phase. Sputum smear converted to negative at month 2.',
    isDemoSimulation: true,
    weightLog: [
      { date: '2026-06-20', weightKg: 61.0 },
      { date: '2026-07-15', weightKg: 63.5 },
      { date: '2026-08-01', weightKg: 65.2 },
      { date: '2026-08-19', weightKg: 66.8 },
    ],
    symptomSeverityScoreLog: [
      { date: '2026-06-20', score: 7.8 },
      { date: '2026-07-15', score: 4.2 },
      { date: '2026-08-01', score: 2.1 },
      { date: '2026-08-19', score: 1.0 },
    ],
    medications: [
      {
        id: 'med_003',
        name: 'Rifampicin + Isoniazid (2-FDC HR)',
        dosage: '150mg/75mg (3 tablets daily)',
        frequency: 'Daily morning (Continuation Phase)',
        notes: 'Supervised weekly clinic pill count.',
      },
    ],
    doseLogs: [
      {
        id: 'dose_004',
        treatmentPlanId: 'tx_007',
        patientId: 'pat_007',
        date: '2026-08-20',
        medicationName: 'Rifampicin + Isoniazid (2-FDC HR)',
        status: 'TAKEN',
        patientNote: 'Weekly blister pack verified.',
        doctorNote: 'Pill count matched expectations.',
        loggedAt: '2026-08-20T10:00:00Z',
        isDemoSimulation: true,
      },
      {
        id: 'dose_005',
        treatmentPlanId: 'tx_007',
        patientId: 'pat_007',
        date: '2026-07-28',
        medicationName: 'Rifampicin + Isoniazid (2-FDC HR)',
        status: 'MISSED',
        patientNote: 'Missed due to travel delay.',
        doctorNote: 'Extra dose taken next morning; adherence re-emphasized.',
        loggedAt: '2026-07-28T20:00:00Z',
        isDemoSimulation: true,
      },
    ],
    sideEffects: [
      {
        id: 'se_002',
        treatmentPlanId: 'tx_007',
        patientId: 'pat_007',
        symptom: 'Orange discoloration of urine and tears',
        severity: 'MILD',
        date: '2026-06-22',
        notes: 'Expected benign side effect of Rifampicin. Patient reassured.',
        status: 'RESOLVED',
        reportedBy: 'Patient',
        doctorActionNote: 'Patient education completed.',
        isDemoSimulation: true,
      },
    ],
    nextAppointmentDate: '2026-09-10',
  },
];

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: 'evt_001',
    patientId: 'pat_001',
    timestamp: '2026-08-20T04:30:00Z',
    type: 'TREATMENT_STARTED',
    title: 'Standard First-Line 4-FDC Treatment Initiated',
    description: 'Patient enrolled in Directly Observed Therapy (DOTS) intensive phase (2HRZE daily). Initial medications dispensed under nurse supervision.',
    authorName: 'Dr. Sarah Chen, MD',
    authorRole: 'Senior Pulmonologist',
    severity: 'success',
  },
  {
    id: 'evt_002',
    patientId: 'pat_001',
    timestamp: '2026-08-19T16:10:00Z',
    type: 'DOCTOR_REVIEW',
    title: 'Clinical Case Validation & Decision Sign-off',
    description: 'Dr. Sarah Chen reviewed multimodal AI risk synthesis (84% score), GeneXpert MTB high load, and bilateral apical cavitation. Confirmed high suspicion of active pulmonary TB.',
    authorName: 'Dr. Sarah Chen, MD',
    authorRole: 'Senior Pulmonologist',
    severity: 'alert',
  },
  {
    id: 'evt_003',
    patientId: 'pat_001',
    timestamp: '2026-08-19T14:40:00Z',
    type: 'LAB_RESULT_RECEIVED',
    title: 'GeneXpert MTB/RIF Ultra Assay Reported',
    description: 'Molecular analysis positive for Mycobacterium tuberculosis complex with high bacterial load. Rifampicin resistance NOT detected.',
    authorName: 'Dr. Mansur Zokirov',
    authorRole: 'Reference Lab Pathologist',
    severity: 'alert',
  },
  {
    id: 'evt_004',
    patientId: 'pat_001',
    timestamp: '2026-08-19T14:30:12Z',
    type: 'AI_ANALYSIS_COMPLETED',
    title: 'AI Multimodal Risk Index Synthesized: 84% (High Risk)',
    description: 'Deep CNN radiograph model flagged right upper lobe cavitation (0.96 confidence). Acoustic cough model detected abnormal explosive phase (81 index).',
    authorName: 'TBDetect AI Diagnostic Engine v3.4',
    authorRole: 'Clinical AI Decision Support',
    severity: 'warning',
  },
  {
    id: 'evt_005',
    patientId: 'pat_001',
    timestamp: '2026-08-19T14:30:00Z',
    type: 'XRAY_UPLOADED',
    title: 'PA Chest Radiograph Uploaded & DICOM Validated',
    description: 'High-resolution DICOM PA radiograph acquired on Siemens Multix Impact successfully processed.',
    authorName: 'Elena Smirnova, RN',
    authorRole: 'Medical Staff',
    severity: 'info',
  },
  {
    id: 'evt_006',
    patientId: 'pat_001',
    timestamp: '2026-08-19T13:45:00Z',
    type: 'SYMPTOM_ASSESSMENT',
    title: 'WHO Symptom Intelligence Questionnaire Completed',
    description: 'Documented 4-week persistent cough, hemoptysis streaks, drenching night sweats, and 5.2 kg weight loss.',
    authorName: 'Dr. Sarah Chen, MD',
    authorRole: 'Senior Pulmonologist',
    severity: 'warning',
  },
  {
    id: 'evt_007',
    patientId: 'pat_001',
    timestamp: '2026-07-10T09:30:00Z',
    type: 'PATIENT_REGISTERED',
    title: 'Patient Dossier Created in Clinic Registry',
    description: 'Patient registered with national health ID TB-2026-089. Household exposure history documented.',
    authorName: 'Bekzod Tulyaganov',
    authorRole: 'Clinic Administrator',
    severity: 'info',
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif_001',
    title: 'Critical Risk Patient Triage Required',
    message: 'Patient Bekhzod Tursunov (TB-2026-118) flagged with 92% AI risk and MDR-TB GeneXpert resistance.',
    timestamp: '10 minutes ago',
    type: 'HIGH_RISK_ALERT',
    read: false,
    patientId: 'pat_003',
    patientName: 'Bekhzod Tursunov',
    severity: 'critical',
  },
  {
    id: 'notif_002',
    title: 'Doctor Review Pending: Rustam Karimov',
    message: 'Multimodal screening complete (Risk Score: 84%). Please validate findings and sign clinical dossier.',
    timestamp: '45 minutes ago',
    type: 'REVIEW_PENDING',
    read: false,
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    severity: 'warning',
  },
  {
    id: 'notif_003',
    title: 'New Confirmatory GeneXpert Lab Result',
    message: 'GeneXpert MTB/RIF result reported for Nodira Aliyeva (TB-2026-104).',
    timestamp: '2 hours ago',
    type: 'LAB_READY',
    read: true,
    patientId: 'pat_002',
    patientName: 'Nodira Aliyeva',
    severity: 'info',
  },
  {
    id: 'notif_004',
    title: 'Follow-up Consultation Due',
    message: 'Sherzod Rakhimov is scheduled for 2-month DOTS continuation phase evaluation tomorrow.',
    timestamp: '4 hours ago',
    type: 'FOLLOWUP_DUE',
    read: true,
    patientId: 'pat_007',
    patientName: 'Sherzod Rakhimov',
    severity: 'info',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'aud_001',
    timestamp: '2026-08-20T05:31:12Z',
    userId: 'usr_doc_0',
    userName: 'Sharipova Dinora',
    userRole: 'DOCTOR',
    action: 'VIEW_PATIENT_DOSSIER',
    module: 'Patients',
    resourceType: 'PATIENT',
    resourceId: 'pat_001',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    ipAddress: '192.168.1.45',
    status: 'SUCCESS',
    details: 'Accessed longitudinal clinical timeline and lab results for Rustam Karimov (TB-2026-089)',
  },
  {
    id: 'aud_002',
    timestamp: '2026-08-20T04:30:00Z',
    userId: 'usr_doc_1',
    userName: 'Dr. Sarah Chen, MD',
    userRole: 'DOCTOR',
    action: 'UPDATE_TREATMENT_PLAN',
    module: 'Treatment',
    resourceType: 'TREATMENT',
    resourceId: 'tx_001',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    ipAddress: '192.168.1.45',
    status: 'SUCCESS',
    details: 'Updated dosage for 2HRZE standard 6-month DOTS regimen; verified adherence at 93.3%',
  },
  {
    id: 'aud_003',
    timestamp: '2026-08-19T17:15:00Z',
    userId: 'usr_doc_0',
    userName: 'Sharipova Dinora',
    userRole: 'DOCTOR',
    action: 'DOWNLOAD_CLINICAL_REPORT',
    module: 'X-Ray AI',
    resourceType: 'XRAY',
    resourceId: 'xray_001',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    ipAddress: '192.168.1.45',
    status: 'SUCCESS',
    details: 'Exported cryptographic clinical dossier and radiograph report for Rustam Karimov (PDF/CSV)',
  },
  {
    id: 'aud_004',
    timestamp: '2026-08-19T16:10:00Z',
    userId: 'usr_doc_1',
    userName: 'Dr. Sarah Chen, MD',
    userRole: 'DOCTOR',
    action: 'SUBMIT_DOCTOR_REVIEW',
    module: 'X-Ray AI',
    resourceType: 'XRAY',
    resourceId: 'xray_001',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    ipAddress: '192.168.1.45',
    status: 'SUCCESS',
    details: 'Digitally signed clinical confirmation for X-Ray xray_001 with CONFIRMED_SUSPICION',
  },
  {
    id: 'aud_005',
    timestamp: '2026-08-19T15:20:00Z',
    userId: 'usr_staff_1',
    userName: 'Elena Smirnova, RN',
    userRole: 'MEDICAL_STAFF',
    action: 'RECORD_COUGH_AUDIO',
    module: 'Cough AI',
    resourceType: 'PATIENT',
    resourceId: 'cgh_001',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    ipAddress: '192.168.1.88',
    status: 'SUCCESS',
    details: 'Captured 8.4-second explosive acoustic cough recording; extracted acoustic spectral signature',
  },
  {
    id: 'aud_006',
    timestamp: '2026-08-19T14:45:00Z',
    userId: 'usr_staff_1',
    userName: 'Elena Smirnova, RN',
    userRole: 'MEDICAL_STAFF',
    action: 'ADD_LABORATORY_RESULT',
    module: 'Laboratory',
    resourceType: 'LAB_RESULT',
    resourceId: 'lab_001',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    ipAddress: '192.168.1.88',
    status: 'SUCCESS',
    details: 'Uploaded GeneXpert MTB/RIF assay: MTB DETECTED (High), RIF RESISTANCE NOT DETECTED',
  },
  {
    id: 'aud_007',
    timestamp: '2026-08-19T14:30:12Z',
    userId: 'system_ai_engine',
    userName: 'TBDetect AI Inference Service',
    userRole: 'ADMIN',
    action: 'RUN_AI_INFERENCE',
    module: 'AI Engine',
    resourceType: 'XRAY',
    resourceId: 'xray_001',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    ipAddress: '10.0.4.12',
    status: 'SUCCESS',
    details: 'Computed 84% multimodal risk score via CNN ResNet-101 + Audio Spectrogram engine',
  },
  {
    id: 'aud_008',
    timestamp: '2026-08-19T14:30:00Z',
    userId: 'usr_staff_1',
    userName: 'Elena Smirnova, RN',
    userRole: 'MEDICAL_STAFF',
    action: 'UPLOAD_DICOM_XRAY',
    module: 'X-Ray AI',
    resourceType: 'XRAY',
    resourceId: 'xray_001',
    patientId: 'pat_001',
    patientName: 'Rustam Karimov',
    ipAddress: '192.168.1.88',
    status: 'SUCCESS',
    details: 'Uploaded 42MB DICOM PA radiograph acquired on Siemens Multix Impact for Rustam Karimov',
  },
  {
    id: 'aud_009',
    timestamp: '2026-08-19T11:00:00Z',
    userId: 'usr_doc_1',
    userName: 'Dr. Sarah Chen, MD',
    userRole: 'DOCTOR',
    action: 'DELETE_SCREENING_STUDY',
    module: 'Cough AI',
    resourceType: 'PATIENT',
    resourceId: 'cgh_archived_99',
    patientId: 'pat_002',
    patientName: 'Nodira Aliyeva',
    ipAddress: '192.168.1.45',
    status: 'SUCCESS',
    details: 'Purged corrupted noisy audio sample per physician request and initiated retake',
  },
  {
    id: 'aud_010',
    timestamp: '2026-08-18T16:45:00Z',
    userId: 'usr_admin_1',
    userName: 'Bekzod Tulyaganov',
    userRole: 'CLINIC_ADMIN',
    action: 'EXPORT_EPIDEMIOLOGY_REPORT',
    module: 'Analytics',
    resourceType: 'SYSTEM_CONFIG',
    resourceId: 'cln_central_1',
    ipAddress: '192.168.1.12',
    status: 'SUCCESS',
    details: 'Exported de-identified monthly regional TB screening cohort metrics in CSV format',
  },
  {
    id: 'aud_011',
    timestamp: '2026-08-18T14:10:00Z',
    userId: 'usr_doc_2',
    userName: 'Dr. Alisher Navoi, PhD',
    userRole: 'DOCTOR',
    action: 'VIEW_PATIENT_DOSSIER',
    module: 'Patients',
    resourceType: 'PATIENT',
    resourceId: 'pat_003',
    patientId: 'pat_003',
    patientName: 'Bekhzod Tursunov',
    ipAddress: '192.168.1.48',
    status: 'SUCCESS',
    details: 'Audited MDR-TB emergency clinical profile and sputum AFB 3+ smear records',
  },
];

export const mockAnalyticsSummary: AnalyticsSummary = {
  totalPatients: 1480,
  screeningsThisMonth: 342,
  highRiskCases: 54,
  pendingDoctorReviews: 12,
  activeTreatments: 86,
  adherenceRateAverage: 94.8,
  avgReviewTurnaroundHours: 1.8,
  monthlyTrend: [
    { month: 'Mar', screenings: 180, highRisk: 28, confirmed: 22 },
    { month: 'Apr', screenings: 210, highRisk: 34, confirmed: 26 },
    { month: 'May', screenings: 260, highRisk: 42, confirmed: 35 },
    { month: 'Jun', screenings: 290, highRisk: 46, confirmed: 38 },
    { month: 'Jul', screenings: 315, highRisk: 49, confirmed: 41 },
    { month: 'Aug', screenings: 342, highRisk: 54, confirmed: 45 },
  ],
  riskDistribution: [
    { name: 'Low Risk (<30%)', value: 62, color: '#10b981' },
    { name: 'Moderate Risk (30-65%)', value: 24, color: '#f59e0b' },
    { name: 'High Risk (65-85%)', value: 10, color: '#f97316' },
    { name: 'Critical (>85%)', value: 4, color: '#ef4444' },
  ],
  symptomFrequency: [
    { symptom: 'Persistent Cough (>2 wks)', count: 284, percentage: 83.0 },
    { symptom: 'Nocturnal Sweats', count: 198, percentage: 57.8 },
    { symptom: 'Unexplained Weight Loss', count: 172, percentage: 50.2 },
    { symptom: 'Low-grade Fever', count: 165, percentage: 48.2 },
    { symptom: 'Hemoptysis (Blood in sputum)', count: 48, percentage: 14.0 },
    { symptom: 'Pleuritic Chest Pain', count: 110, percentage: 32.1 },
    { symptom: 'Fatigue & Malaise', count: 230, percentage: 67.2 },
  ],
  modalityContribution: [
    { name: 'Chest X-Ray Deep CNN', weight: 42 },
    { name: 'Symptom Algorithmic Matrix', weight: 28 },
    { name: 'Acoustic Cough Spectrogram', weight: 18 },
    { name: 'Epidemiological Exposure Score', weight: 12 },
  ],
};
