import { Clinic } from '../types';

export interface UzbekistanRegionMeta {
  key: string;
  nameUz: string;
  nameRu: string;
  nameEn: string;
  centerUz: string;
  centerRu: string;
  centerEn: string;
  tbCenterNameUz: string;
  tbCenterNameRu: string;
  tbCenterNameEn: string;
  servicesUz: string[];
  servicesRu: string[];
  servicesEn: string[];
}

export const UZBEKISTAN_REGIONS: UzbekistanRegionMeta[] = [
  {
    key: 'tashkent_city',
    nameUz: 'Toshkent shahri',
    nameRu: 'город Ташкент',
    nameEn: 'Tashkent City',
    centerUz: 'Toshkent',
    centerRu: 'Ташкент',
    centerEn: 'Tashkent',
    tbCenterNameUz: 'Respublika Ixtisoslashtirilgan Ftiziatriya va Pulmonologiya Markazi (RIFP IATM)',
    tbCenterNameRu: 'Республиканский специализированный научно-практический медицинский центр фтизиатрии и пульмонологии (РСНПМЦФиП)',
    tbCenterNameEn: 'Republican Specialized Scientific & Practical Medical Center of Phthisiology & Pulmonology',
    servicesUz: ['GeneXpert MTB/RIF Ultra', 'Bactec MGIT 960', 'KT va Raqamli rentgen', 'Torakal jarrohlik', 'DOTS ambulator monitoring'],
    servicesRu: ['GeneXpert MTB/RIF Ultra', 'Bactec MGIT 960', 'КТ и Цифровой рентген', 'Торакальная хирургия', 'Амбулаторный DOTS'],
    servicesEn: ['GeneXpert MTB/RIF Ultra', 'Bactec MGIT 960', 'CT & Digital Radiography', 'Thoracic Surgery', 'Outpatient DOTS'],
  },
  {
    key: 'karakalpakstan',
    nameUz: "Qoraqalpog'iston Respublikasi",
    nameRu: 'Республика Каракалпакстан',
    nameEn: 'Republic of Karakalpakstan',
    centerUz: 'Nukus',
    centerRu: 'Нукус',
    centerEn: 'Nukus',
    tbCenterNameUz: "Qoraqalpog'iston Respublikasi Ftiziatriya va Pulmonologiya Markazi",
    tbCenterNameRu: 'Республиканский центр фтизиатрии и пульмонологии Республики Каракалпакстан',
    tbCenterNameEn: 'Center of Phthisiology & Pulmonology of Karakalpakstan',
    servicesUz: ['GeneXpert MTB/RIF', 'Sputum mikroskopiyasi', 'Statsionar ftiziatriya', 'DOTS nazorati', 'Rentgen AI skrining'],
    servicesRu: ['GeneXpert MTB/RIF', 'Микроскопия мокроты', 'Стационар', 'DOTS-контроль', 'Рентген ИИ'],
    servicesEn: ['GeneXpert MTB/RIF', 'Sputum Smear Microscopy', 'Inpatient Care', 'DOTS Protocol', 'X-Ray AI Screening'],
  },
  {
    key: 'andijan',
    nameUz: 'Andijon viloyati',
    nameRu: 'Андижанская область',
    nameEn: 'Andijan Region',
    centerUz: 'Andijon',
    centerRu: 'Андижан',
    centerEn: 'Andijan',
    tbCenterNameUz: 'Andijon viloyat Ftiziatriya va Pulmonologiya Markazi',
    tbCenterNameRu: 'Андижанский областной центр фтизиатрии и пульмонологии',
    tbCenterNameEn: 'Andijan Regional Center of Phthisiology & Pulmonology',
    servicesUz: ['Molekulyar-genetik laboratoriya', 'Raqamli rentgenografiya', 'Statsionar davolash', 'Ambulator DOTS'],
    servicesRu: ['Молекулярно-генетическая лаборатория', 'Цифровая рентгенография', 'Стационар', 'Амбулаторный DOTS'],
    servicesEn: ['Molecular Diagnostics (GeneXpert)', 'Digital X-Ray', 'Inpatient Facility', 'Outpatient DOTS'],
  },
  {
    key: 'bukhara',
    nameUz: 'Buxoro viloyati',
    nameRu: 'Бухарская область',
    nameEn: 'Bukhara Region',
    centerUz: 'Buxoro',
    centerRu: 'Бухара',
    centerEn: 'Bukhara',
    tbCenterNameUz: 'Buxoro viloyat Ftiziatriya va Pulmonologiya Markazi',
    tbCenterNameRu: 'Бухарский областной центр фтизиатрии и пульмонологии',
    tbCenterNameEn: 'Bukhara Regional Center of Phthisiology & Pulmonology',
    servicesUz: ['GeneXpert MTB/RIF diagnostikasi', 'Rentgen tekshiruvi', 'DOTS xizmati', 'Pulmonologik reabilitatsiya'],
    servicesRu: ['Диагностика GeneXpert MTB/RIF', 'Рентген-диагностика', 'Служба DOTS', 'Пульмонологическая реабилитация'],
    servicesEn: ['GeneXpert MTB/RIF Assay', 'X-Ray Diagnostics', 'DOTS Service', 'Pulmonology Rehabilitation'],
  },
  {
    key: 'jizzakh',
    nameUz: 'Jizzax viloyati',
    nameRu: 'Джизакская область',
    nameEn: 'Jizzakh Region',
    centerUz: 'Jizzax',
    centerRu: 'Джизак',
    centerEn: 'Jizzakh',
    tbCenterNameUz: 'Jizzax viloyat Ftiziatriya va Pulmonologiya Markazi',
    tbCenterNameRu: 'Джизакский областной центр фтизиатрии и пульмонологии',
    tbCenterNameEn: 'Jizzakh Regional Center of Phthisiology & Pulmonology',
    servicesUz: ["Balg'am mikroskopiyasi", 'Flyuorografiya va Rentgen', 'DOTS monitoring', 'Dispanser hisobi'],
    servicesRu: ['Микроскопия мокроты', 'Флюорография и Рентген', 'Мониторинг DOTS', 'Диспансерный учет'],
    servicesEn: ['Sputum Smear', 'Fluorography & X-Ray', 'DOTS Monitoring', 'Dispensary Registry'],
  },
  {
    key: 'kashkadarya',
    nameUz: 'Qashqadaryo viloyati',
    nameRu: 'Кашкадарьинская область',
    nameEn: 'Kashkadarya Region',
    centerUz: 'Qarshi',
    centerRu: 'Карши',
    centerEn: 'Karshi',
    tbCenterNameUz: 'Qashqadaryo viloyat Ftiziatriya va Pulmonologiya Markazi',
    tbCenterNameRu: 'Кашкадарьинский областной центр фтизиатрии и пульмонологии',
    tbCenterNameEn: 'Kashkadarya Regional Center of Phthisiology & Pulmonology',
    servicesUz: ['GeneXpert MTB/RIF tahlili', 'Ko‘krak qafasi rentgeni', 'Dori ta‘minoti va monitoring', 'Statsionar'],
    servicesRu: ['Анализ GeneXpert MTB/RIF', 'Рентген грудной клетки', 'Лекарственное обеспечение и учет', 'Стационар'],
    servicesEn: ['GeneXpert MTB/RIF Assay', 'Chest Radiography', 'Medication Logistics & DOTS', 'Inpatient Facility'],
  },
  {
    key: 'navoi',
    nameUz: 'Navoiy viloyati',
    nameRu: 'Навоийская область',
    nameEn: 'Navoi Region',
    centerUz: 'Navoiy / Karmana',
    centerRu: 'Навои / Кармана',
    centerEn: 'Navoi / Karmana',
    tbCenterNameUz: 'Navoiy viloyat Ftiziatriya va Pulmonologiya Markazi',
    tbCenterNameRu: 'Навоийский областной центр фтизиатрии и пульмонологии',
    tbCenterNameEn: 'Navoi Regional Center of Phthisiology & Pulmonology',
    servicesUz: ['Mikrobiologik laboratoriya', 'Raqamli rentgenografiya', 'DOTS nazorati', "Kasallarni ro'yxatga olish"],
    servicesRu: ['Микробиологическая лаборатория', 'Цифровая рентгенография', 'Контроль DOTS', 'Регистрация пациентов'],
    servicesEn: ['Microbiology Lab', 'Digital X-Ray', 'DOTS Adherence Oversight', 'Cohort Registry'],
  },
  {
    key: 'namangan',
    nameUz: 'Namangan viloyati',
    nameRu: 'Наманганская область',
    nameEn: 'Namangan Region',
    centerUz: 'Namangan',
    centerRu: 'Наманган',
    centerEn: 'Namangan',
    tbCenterNameUz: 'Namangan viloyat Ftiziatriya va Pulmonologiya Markazi',
    tbCenterNameRu: 'Наманганский областной центр фтизиатрии и пульмонологии',
    tbCenterNameEn: 'Namangan Regional Center of Phthisiology & Pulmonology',
    servicesUz: ['GeneXpert MTB/RIF Ultra', 'Mikroskopik tekshiruv', 'Rentgenografiya', 'Ambulator DOTS nazorati'],
    servicesRu: ['GeneXpert MTB/RIF Ultra', 'Микроскопическое исследование', 'Рентгенография', 'Амбулаторный DOTS'],
    servicesEn: ['GeneXpert MTB/RIF Ultra', 'Microscopic Smear', 'Radiography', 'Ambulatory DOTS'],
  },
  {
    key: 'samarkand',
    nameUz: 'Samarqand viloyati',
    nameRu: 'Самаркандская область',
    nameEn: 'Samarkand Region',
    centerUz: 'Samarqand',
    centerRu: 'Самарканд',
    centerEn: 'Samarkand',
    tbCenterNameUz: 'Samarqand viloyat Ftiziatriya va Pulmonologiya Markazi',
    tbCenterNameRu: 'Самаркандский областной центр фтизиатрии и пульмонологии',
    tbCenterNameEn: 'Samarkand Regional Center of Phthisiology & Pulmonology',
    servicesUz: ['Molekulyar diagnostika (GeneXpert)', 'Raqamli rentgen va flyuorografiya', 'DOTS nazorati', 'Statsionar davolash'],
    servicesRu: ['Молекулярная диагностика (GeneXpert)', 'Цифровой рентген и флюорография', 'Контроль DOTS', 'Стационар'],
    servicesEn: ['Molecular Diagnostics (GeneXpert)', 'Digital X-Ray & Screening', 'DOTS Care', 'Inpatient Treatment'],
  },
  {
    key: 'surkhandarya',
    nameUz: 'Surxondaryo viloyati',
    nameRu: 'Сурхандарьинская область',
    nameEn: 'Surkhandarya Region',
    centerUz: 'Termiz',
    centerRu: 'Термез',
    centerEn: 'Termez',
    tbCenterNameUz: 'Surxondaryo viloyat Ftiziatriya va Pulmonologiya Markazi',
    tbCenterNameRu: 'Сурхандарьинский областной центр фтизиатрии и пульмонологии',
    tbCenterNameEn: 'Surkhandarya Regional Center of Phthisiology & Pulmonology',
    servicesUz: ['Bakterioskopiya va ekma', 'Flyuorografiya', "Ko'chma rentgen skrining", 'DOTS monitoring'],
    servicesRu: ['Бактериоскопия и посев', 'Флюорография', 'Мобильный рентген-скрининг', 'Мониторинг DOTS'],
    servicesEn: ['AFB Smear & Culture', 'Fluorography', 'Mobile X-Ray Field Unit', 'DOTS Oversight'],
  },
  {
    key: 'syrdarya',
    nameUz: 'Sirdaryo viloyati',
    nameRu: 'Сырдарьинская область',
    nameEn: 'Syrdarya Region',
    centerUz: 'Guliston',
    centerRu: 'Гулистан',
    centerEn: 'Gulistan',
    tbCenterNameUz: 'Sirdaryo viloyat Ftiziatriya va Pulmonologiya Markazi',
    tbCenterNameRu: 'Сырдарьинский областной центр фтизиатрии и пульмонологии',
    tbCenterNameEn: 'Syrdarya Regional Center of Phthisiology & Pulmonology',
    servicesUz: ['Sil mikobakteriyasini aniqlash', 'Raqamli rentgen', 'Nazoratli davolash (DOTS)', 'Dispanser hisobi'],
    servicesRu: ['Определение микобактерий ТБ', 'Цифровой рентген', 'Контролируемое лечение (DOTS)', 'Диспансер'],
    servicesEn: ['MTB Identification', 'Digital X-Ray', 'Directly Observed Therapy (DOTS)', 'Dispensary Cohort'],
  },
  {
    key: 'fergana',
    nameUz: "Farg'ona viloyati",
    nameRu: 'Ферганская область',
    nameEn: 'Fergana Region',
    centerUz: "Farg'ona",
    centerRu: 'Фергана',
    centerEn: 'Fergana',
    tbCenterNameUz: "Farg'ona viloyat Ftiziatriya va Pulmonologiya Markazi",
    tbCenterNameRu: 'Ферганский областной центр фтизиатрии и пульмонологии',
    tbCenterNameEn: 'Fergana Regional Center of Phthisiology & Pulmonology',
    servicesUz: ['GeneXpert MTB/RIF', 'Sputum mikroskopiyasi', 'Rentgen diagnostika', 'DOTS kabineti', 'Bolalar ftiziatriyasi'],
    servicesRu: ['GeneXpert MTB/RIF', 'Микроскопия мокроты', 'Рентген-диагностика', 'Кабинет DOTS', 'Детская фтизиатрия'],
    servicesEn: ['GeneXpert MTB/RIF', 'Sputum Smear', 'X-Ray Diagnostics', 'DOTS Unit', 'Pediatric TB Care'],
  },
  {
    key: 'tashkent_region',
    nameUz: 'Toshkent viloyati',
    nameRu: 'Ташкентская область',
    nameEn: 'Tashkent Region',
    centerUz: "Yangiyo'l / Nurafshon",
    centerRu: 'Янгиюль / Нурафшон',
    centerEn: 'Yangiyul / Nurafshon',
    tbCenterNameUz: 'Toshkent viloyat Ftiziatriya va Pulmonologiya Markazi',
    tbCenterNameRu: 'Ташкентский областной центр фтизиатрии и пульмонологии',
    tbCenterNameEn: 'Tashkent Regional Center of Phthisiology & Pulmonology',
    servicesUz: ['Hududiy ftiziatriya xizmati', 'Rentgen flyuorografiya', 'GeneXpert tahlili', 'DOTS monitoring'],
    servicesRu: ['Областная фтизиатрическая служба', 'Рентген и флюорография', 'Анализ GeneXpert', 'Мониторинг DOTS'],
    servicesEn: ['Regional TB Service', 'Chest X-Ray & Screening', 'GeneXpert Assay', 'DOTS Monitoring'],
  },
  {
    key: 'khorezm',
    nameUz: 'Xorazm viloyati',
    nameRu: 'Хорезмская область',
    nameEn: 'Khorezm Region',
    centerUz: 'Urganch',
    centerRu: 'Ургенч',
    centerEn: 'Urgench',
    tbCenterNameUz: 'Xorazm viloyat Ftiziatriya va Pulmonologiya Markazi',
    tbCenterNameRu: 'Хорезмский областной центр фтизиатрии и пульмонологии',
    tbCenterNameEn: 'Khorezm Regional Center of Phthisiology & Pulmonology',
    servicesUz: ['GeneXpert MTB/RIF diagnostikasi', 'Rentgenografiya va flyuorografiya', 'DOTS ambulator xizmati', 'Reabilitatsiya'],
    servicesRu: ['Диагностика GeneXpert MTB/RIF', 'Рентгенография и флюорография', 'Амбулаторная служба DOTS', 'Реабилитация'],
    servicesEn: ['GeneXpert MTB/RIF Diagnostics', 'Radiography & Screening', 'Outpatient DOTS', 'Respiratory Rehabilitation'],
  },
];

export const REAL_UZBEKISTAN_CLINICS: Clinic[] = [
  {
    id: 'cln_uz_rifp',
    name: 'Respublika Ixtisoslashtirilgan Ftiziatriya va Pulmonologiya Ilmiy-Amaliy Tibbiyot Markazi (RIFP IATM)',
    nameUz: 'Respublika Ixtisoslashtirilgan Ftiziatriya va Pulmonologiya Ilmiy-Amaliy Tibbiyot Markazi (RIFP IATM)',
    nameRu: 'Республиканский специализированный научно-практический медицинский центр фтизиатрии и пульмонологии (РСНПМЦФиП)',
    nameEn: 'Republican Specialized Scientific & Practical Medical Center of Phthisiology and Pulmonology',
    organizationType: 'PULMONOLOGY_CENTER',
    region: 'Toshkent shahri',
    regionKey: 'tashkent_city',
    district: 'Chilonzor tumani',
    address: 'Toshkent sh., Chilonzor tumani, Al-Xorazmiy ko‘chasi, 1',
    contactEmail: 'info@rifp.uz',
    contactPhone: '+998 71 278 04 70',
    website: 'http://rifp.uz',
    adminName: 'Prof. N.N. Parpieva',
    activeUsersCount: 42,
    totalPatientsCount: 3120,
    activeScreeningsCount: 480,
    status: 'ACTIVE',
    licenseExpiry: '2030-12-31',
    isTbSpecialized: true,
    services: ['GeneXpert MTB/RIF Ultra', 'Bactec MGIT 960', 'KT va Raqamli rentgen', 'Torakal jarrohlik', 'DOTS ambulator monitoring', 'Bolalar ftiziatriyasi'],
    lastVerifiedDate: '2026-08-15',
    verificationSource: 'O‘zbekiston Respublikasi Sog‘liqni Saqlash Vazirligi (ssv.uz)',
    googleMapsQuery: 'Toshkent sh., Chilonzor tumani, Al-Xorazmiy ko‘chasi, 1',
  },
  {
    id: 'cln_uz_tash_city_disp',
    name: 'Toshkent shahar Ftiziatriya va Pulmonologiya Markazi (1-son silga qarshi dispanser)',
    nameUz: 'Toshkent shahar Ftiziatriya va Pulmonologiya Markazi (1-son silga qarshi dispanser)',
    nameRu: 'Городской центр фтизиатрии и пульмонологии г. Ташкента (Противотуберкулезный диспансер №1)',
    nameEn: 'Tashkent City Center of Phthisiology and Pulmonology (Dispensary #1)',
    organizationType: 'DISPENSARY',
    region: 'Toshkent shahri',
    regionKey: 'tashkent_city',
    district: 'Olmazor tumani',
    address: 'Toshkent sh., Olmazor tumani, Qorasaroy ko‘chasi, 341',
    contactEmail: 'contact@tash-tb.uz',
    contactPhone: '+998 71 248 12 35',
    website: "Ma'lumot mavjud emas",
    adminName: 'Dr. B.A. Mirzayev',
    activeUsersCount: 22,
    totalPatientsCount: 1680,
    activeScreeningsCount: 195,
    status: 'ACTIVE',
    licenseExpiry: '2029-06-30',
    isTbSpecialized: true,
    services: ["Balg'am mikroskopiyasi", 'Flyuorografiya va Rentgen', 'DOTS kabineti', 'Hududiy dispanser nazorati'],
    lastVerifiedDate: '2026-08-10',
    verificationSource: 'Toshkent shahar Sog‘liqni saqlash bosh boshqarmasi',
    googleMapsQuery: 'Toshkent sh., Olmazor tumani, Qorasaroy ko‘chasi, 341',
  },
  {
    id: 'cln_uz_nukus_tb',
    name: 'Qoraqalpog‘iston Respublikasi Ftiziatriya va Pulmonologiya Markazi',
    nameUz: 'Qoraqalpog‘iston Respublikasi Ftiziatriya va Pulmonologiya Markazi',
    nameRu: 'Республиканский центр фтизиатрии и пульмонологии Республики Каракалпакстан',
    nameEn: 'Center of Phthisiology & Pulmonology of Karakalpakstan',
    organizationType: 'REGIONAL_HOSPITAL',
    region: "Qoraqalpog'iston Respublikasi",
    regionKey: 'karakalpakstan',
    district: 'Nukus shahri',
    address: 'Nukus sh., Allayar Dosnazarov ko‘chasi, 114',
    contactEmail: 'nukus.tb@ssv.uz',
    contactPhone: '+998 61 222 41 85',
    website: "Ma'lumot mavjud emas",
    adminName: 'Dr. Q.K. Qutlimuratov',
    activeUsersCount: 19,
    totalPatientsCount: 1340,
    activeScreeningsCount: 142,
    status: 'ACTIVE',
    licenseExpiry: '2028-10-15',
    isTbSpecialized: true,
    services: ['GeneXpert MTB/RIF', 'Sputum mikroskopiyasi', 'Statsionar ftiziatriya', 'DOTS nazorati', 'Rentgen AI skrining'],
    lastVerifiedDate: '2026-08-01',
    verificationSource: 'Qoraqalpog‘iston Respublikasi Sog‘liqni saqlash vazirligi',
    googleMapsQuery: 'Nukus sh., Allayar Dosnazarov ko‘chasi, 114',
  },
  {
    id: 'cln_uz_andijan_tb',
    name: 'Andijon viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameUz: 'Andijon viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameRu: 'Андижанский областной центр фтизиатрии и пульмонологии',
    nameEn: 'Andijan Regional Center of Phthisiology & Pulmonology',
    organizationType: 'REGIONAL_HOSPITAL',
    region: 'Andijon viloyati',
    regionKey: 'andijan',
    district: 'Andijon shahri',
    address: 'Andijon sh., Nayman ko‘chasi, 1',
    contactEmail: 'andijan.tb@ssv.uz',
    contactPhone: '+998 74 224 15 62',
    website: "Ma'lumot mavjud emas",
    adminName: 'Dr. O.T. Yusupov',
    activeUsersCount: 26,
    totalPatientsCount: 1850,
    activeScreeningsCount: 210,
    status: 'ACTIVE',
    licenseExpiry: '2028-04-20',
    isTbSpecialized: true,
    services: ['Molekulyar-genetik laboratoriya', 'Raqamli rentgenografiya', 'Statsionar davolash', 'Ambulator DOTS'],
    lastVerifiedDate: '2026-07-28',
    verificationSource: 'Andijon viloyati Sog‘liqni saqlash boshqarmasi',
    googleMapsQuery: 'Andijon sh., Nayman ko‘chasi, 1',
  },
  {
    id: 'cln_uz_bukhara_tb',
    name: 'Buxoro viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameUz: 'Buxoro viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameRu: 'Бухарский областной центр фтизиатрии и пульмонологии',
    nameEn: 'Bukhara Regional Center of Phthisiology & Pulmonology',
    organizationType: 'REGIONAL_HOSPITAL',
    region: 'Buxoro viloyati',
    regionKey: 'bukhara',
    district: 'Buxoro shahri',
    address: 'Buxoro sh., G‘ijduvon ko‘chasi, 82',
    contactEmail: 'bukhara.tb@ssv.uz',
    contactPhone: '+998 65 221 54 30',
    website: "Ma'lumot mavjud emas",
    adminName: 'Dr. M.Sh. Boltayev',
    activeUsersCount: 18,
    totalPatientsCount: 1190,
    activeScreeningsCount: 125,
    status: 'ACTIVE',
    licenseExpiry: '2028-09-12',
    isTbSpecialized: true,
    services: ['GeneXpert MTB/RIF diagnostikasi', 'Rentgen tekshiruvi', 'DOTS xizmati', 'Pulmonologik reabilitatsiya'],
    lastVerifiedDate: '2026-08-05',
    verificationSource: 'Buxoro viloyati Sog‘liqni saqlash boshqarmasi',
    googleMapsQuery: 'Buxoro sh., G‘ijduvon ko‘chasi, 82',
  },
  {
    id: 'cln_uz_jizzakh_tb',
    name: 'Jizzax viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameUz: 'Jizzax viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameRu: 'Джизакский областной центр фтизиатрии и пульмонологии',
    nameEn: 'Jizzakh Regional Center of Phthisiology & Pulmonology',
    organizationType: 'REGIONAL_HOSPITAL',
    region: 'Jizzax viloyati',
    regionKey: 'jizzakh',
    district: 'Jizzax shahri',
    address: 'Jizzax sh., Sh. Rashidov shoh ko‘chasi, 64',
    contactEmail: 'jizzakh.tb@ssv.uz',
    contactPhone: '+998 72 226 31 40',
    website: "Ma'lumot mavjud emas",
    adminName: 'Dr. S.R. Xolmatov',
    activeUsersCount: 14,
    totalPatientsCount: 890,
    activeScreeningsCount: 96,
    status: 'ACTIVE',
    licenseExpiry: '2027-11-18',
    isTbSpecialized: true,
    services: ["Balg'am mikroskopiyasi", 'Flyuorografiya va Rentgen', 'DOTS monitoring', 'Dispanser hisobi'],
    lastVerifiedDate: '2026-07-20',
    verificationSource: 'Jizzax viloyati Sog‘liqni saqlash boshqarmasi',
    googleMapsQuery: 'Jizzax sh., Sh. Rashidov shoh ko‘chasi, 64',
  },
  {
    id: 'cln_uz_kashkadarya_tb',
    name: 'Qashqadaryo viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameUz: 'Qashqadaryo viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameRu: 'Кашкадарьинский областной центр фтизиатрии и пульмонологии',
    nameEn: 'Kashkadarya Regional Center of Phthisiology & Pulmonology',
    organizationType: 'REGIONAL_HOSPITAL',
    region: 'Qashqadaryo viloyati',
    regionKey: 'kashkadarya',
    district: 'Qarshi shahri',
    address: 'Qarshi sh., Islom Karimov ko‘chasi, 215',
    contactEmail: 'kashkadarya.tb@ssv.uz',
    contactPhone: '+998 75 221 08 44',
    website: "Ma'lumot mavjud emas",
    adminName: 'Dr. U.E. Normatov',
    activeUsersCount: 24,
    totalPatientsCount: 1720,
    activeScreeningsCount: 185,
    status: 'ACTIVE',
    licenseExpiry: '2028-05-30',
    isTbSpecialized: true,
    services: ['GeneXpert MTB/RIF tahlili', 'Ko‘krak qafasi rentgeni', 'Dori ta‘minoti va monitoring', 'Statsionar'],
    lastVerifiedDate: '2026-08-08',
    verificationSource: 'Qashqadaryo viloyati Sog‘liqni saqlash boshqarmasi',
    googleMapsQuery: 'Qarshi sh., Islom Karimov ko‘chasi, 215',
  },
  {
    id: 'cln_uz_navoi_tb',
    name: 'Navoiy viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameUz: 'Navoiy viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameRu: 'Навоийский областной центр фтизиатрии и пульмонологии',
    nameEn: 'Navoi Regional Center of Phthisiology & Pulmonology',
    organizationType: 'REGIONAL_HOSPITAL',
    region: 'Navoiy viloyati',
    regionKey: 'navoi',
    district: 'Karmana tumani',
    address: 'Navoiy viloyati, Karmana tumani, Toshkent ko‘chasi, 15',
    contactEmail: 'navoi.tb@ssv.uz',
    contactPhone: '+998 79 223 12 77',
    website: "Ma'lumot mavjud emas",
    adminName: 'Dr. A.B. Qodirov',
    activeUsersCount: 15,
    totalPatientsCount: 760,
    activeScreeningsCount: 88,
    status: 'ACTIVE',
    licenseExpiry: '2027-08-25',
    isTbSpecialized: true,
    services: ['Mikrobiologik laboratoriya', 'Raqamli rentgenografiya', 'DOTS nazorati', "Kasallarni ro'yxatga olish"],
    lastVerifiedDate: '2026-07-15',
    verificationSource: 'Navoiy viloyati Sog‘liqni saqlash boshqarmasi',
    googleMapsQuery: 'Navoiy viloyati, Karmana tumani, Toshkent ko‘chasi, 15',
  },
  {
    id: 'cln_uz_namangan_tb',
    name: 'Namangan viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameUz: 'Namangan viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameRu: 'Наманганский областной центр фтизиатрии и пульмонологии',
    nameEn: 'Namangan Regional Center of Phthisiology & Pulmonology',
    organizationType: 'REGIONAL_HOSPITAL',
    region: 'Namangan viloyati',
    regionKey: 'namangan',
    district: 'Namangan shahri',
    address: 'Namangan sh., Uychi ko‘chasi, 33',
    contactEmail: 'namangan.tb@ssv.uz',
    contactPhone: '+998 69 232 40 18',
    website: "Ma'lumot mavjud emas",
    adminName: 'Dr. F.X. Nishonov',
    activeUsersCount: 25,
    totalPatientsCount: 1690,
    activeScreeningsCount: 178,
    status: 'ACTIVE',
    licenseExpiry: '2028-11-05',
    isTbSpecialized: true,
    services: ['GeneXpert MTB/RIF Ultra', 'Mikroskopik tekshiruv', 'Rentgenografiya', 'Ambulator DOTS nazorati'],
    lastVerifiedDate: '2026-08-11',
    verificationSource: 'Namangan viloyati Sog‘liqni saqlash boshqarmasi',
    googleMapsQuery: 'Namangan sh., Uychi ko‘chasi, 33',
  },
  {
    id: 'cln_uz_samarkand_tb',
    name: 'Samarqand viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameUz: 'Samarqand viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameRu: 'Самаркандский областной центр фтизиатрии и пульмонологии',
    nameEn: 'Samarkand Regional Center of Phthisiology & Pulmonology',
    organizationType: 'REGIONAL_HOSPITAL',
    region: 'Samarqand viloyati',
    regionKey: 'samarkand',
    district: 'Samarqand shahri',
    address: 'Samarqand sh., Spitamen ko‘chasi, 153',
    contactEmail: 'samarkand.tb@ssv.uz',
    contactPhone: '+998 66 233 11 00',
    website: "Ma'lumot mavjud emas",
    adminName: 'Dr. J.K. Ergashev',
    activeUsersCount: 32,
    totalPatientsCount: 2240,
    activeScreeningsCount: 260,
    status: 'ACTIVE',
    licenseExpiry: '2029-03-15',
    isTbSpecialized: true,
    services: ['Molekulyar diagnostika (GeneXpert)', 'Raqamli rentgen va flyuorografiya', 'DOTS nazorati', 'Statsionar davolash'],
    lastVerifiedDate: '2026-08-14',
    verificationSource: 'Samarqand viloyati Sog‘liqni saqlash boshqarmasi',
    googleMapsQuery: 'Samarqand sh., Spitamen ko‘chasi, 153',
  },
  {
    id: 'cln_uz_surkhandarya_tb',
    name: 'Surxondaryo viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameUz: 'Surxondaryo viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameRu: 'Сурхандарьинский областной центр фтизиатрии и пульмонологии',
    nameEn: 'Surkhandarya Regional Center of Phthisiology & Pulmonology',
    organizationType: 'REGIONAL_HOSPITAL',
    region: 'Surxondaryo viloyati',
    regionKey: 'surkhandarya',
    district: 'Termiz shahri',
    address: 'Termiz sh., Al-Hakim at-Termiziy ko‘chasi, 45',
    contactEmail: 'surxondaryo.tb@ssv.uz',
    contactPhone: '+998 76 227 19 82',
    website: "Ma'lumot mavjud emas",
    adminName: 'Dr. O.M. Mirzayev',
    activeUsersCount: 17,
    totalPatientsCount: 1040,
    activeScreeningsCount: 115,
    status: 'ACTIVE',
    licenseExpiry: '2027-12-10',
    isTbSpecialized: true,
    services: ['Bakterioskopiya va ekma', 'Flyuorografiya', "Ko'chma rentgen skrining", 'DOTS monitoring'],
    lastVerifiedDate: '2026-07-22',
    verificationSource: 'Surxondaryo viloyati Sog‘liqni saqlash boshqarmasi',
    googleMapsQuery: 'Termiz sh., Al-Hakim at-Termiziy ko‘chasi, 45',
  },
  {
    id: 'cln_uz_syrdarya_tb',
    name: 'Sirdaryo viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameUz: 'Sirdaryo viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameRu: 'Сырдарьинский областной центр фтизиатрии и пульмонологии',
    nameEn: 'Syrdarya Regional Center of Phthisiology & Pulmonology',
    organizationType: 'REGIONAL_HOSPITAL',
    region: 'Sirdaryo viloyati',
    regionKey: 'syrdarya',
    district: 'Guliston shahri',
    address: 'Guliston sh., Sayxun ko‘chasi, 7',
    contactEmail: 'sirdaryo.tb@ssv.uz',
    contactPhone: '+998 67 225 18 90',
    website: "Ma'lumot mavjud emas",
    adminName: 'Dr. B.H. Rahimov',
    activeUsersCount: 13,
    totalPatientsCount: 680,
    activeScreeningsCount: 74,
    status: 'ACTIVE',
    licenseExpiry: '2027-09-30',
    isTbSpecialized: true,
    services: ['Sil mikobakteriyasini aniqlash', 'Raqamli rentgen', 'Nazoratli davolash (DOTS)', 'Dispanser hisobi'],
    lastVerifiedDate: '2026-07-30',
    verificationSource: 'Sirdaryo viloyati Sog‘liqni saqlash boshqarmasi',
    googleMapsQuery: 'Guliston sh., Sayxun ko‘chasi, 7',
  },
  {
    id: 'cln_uz_fergana_tb',
    name: 'Farg‘ona viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameUz: 'Farg‘ona viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameRu: 'Ферганский областной центр фтизиатрии и пульмонологии',
    nameEn: 'Fergana Regional Center of Phthisiology & Pulmonology',
    organizationType: 'REGIONAL_HOSPITAL',
    region: "Farg'ona viloyati",
    regionKey: 'fergana',
    district: 'Farg‘ona shahri',
    address: 'Farg‘ona sh., Al-Farg‘oniy ko‘chasi, 56',
    contactEmail: 'fergana.tb@ssv.uz',
    contactPhone: '+998 73 224 38 12',
    website: "Ma'lumot mavjud emas",
    adminName: 'Dr. N.M. Xasanova',
    activeUsersCount: 29,
    totalPatientsCount: 2050,
    activeScreeningsCount: 235,
    status: 'ACTIVE',
    licenseExpiry: '2028-07-25',
    isTbSpecialized: true,
    services: ['GeneXpert MTB/RIF', 'Sputum mikroskopiyasi', 'Rentgen diagnostika', 'DOTS kabineti', 'Bolalar ftiziatriyasi'],
    lastVerifiedDate: '2026-08-12',
    verificationSource: 'Farg‘ona viloyati Sog‘liqni saqlash boshqarmasi',
    googleMapsQuery: 'Farg‘ona sh., Al-Farg‘oniy ko‘chasi, 56',
  },
  {
    id: 'cln_uz_tash_reg_tb',
    name: 'Toshkent viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameUz: 'Toshkent viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameRu: 'Ташкентский областной центр фтизиатрии и пульмонологии',
    nameEn: 'Tashkent Regional Center of Phthisiology & Pulmonology',
    organizationType: 'REGIONAL_HOSPITAL',
    region: 'Toshkent viloyati',
    regionKey: 'tashkent_region',
    district: 'Yangiyo‘l shahri',
    address: 'Toshkent viloyati, Yangiyo‘l sh., Samarqand ko‘chasi, 12',
    contactEmail: 'tashkent.obl.tb@ssv.uz',
    contactPhone: '+998 70 602 14 55',
    website: "Ma'lumot mavjud emas",
    adminName: 'Dr. Sh.T. Karimov',
    activeUsersCount: 27,
    totalPatientsCount: 1910,
    activeScreeningsCount: 220,
    status: 'ACTIVE',
    licenseExpiry: '2028-06-18',
    isTbSpecialized: true,
    services: ['Hududiy ftiziatriya xizmati', 'Rentgen flyuorografiya', 'GeneXpert tahlili', 'DOTS monitoring'],
    lastVerifiedDate: '2026-08-02',
    verificationSource: 'Toshkent viloyati Sog‘liqni saqlash boshqarmasi',
    googleMapsQuery: 'Toshkent viloyati, Yangiyo‘l sh., Samarqand ko‘chasi, 12',
  },
  {
    id: 'cln_uz_khorezm_tb',
    name: 'Xorazm viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameUz: 'Xorazm viloyat Ftiziatriya va Pulmonologiya Markazi',
    nameRu: 'Хорезмский областной центр фтизиатрии и пульмонологии',
    nameEn: 'Khorezm Regional Center of Phthisiology & Pulmonology',
    organizationType: 'REGIONAL_HOSPITAL',
    region: 'Xorazm viloyati',
    regionKey: 'khorezm',
    district: 'Urganch shahri',
    address: 'Urganch sh., Xonqa ko‘chasi, 48',
    contactEmail: 'khorezm.tb@ssv.uz',
    contactPhone: '+998 62 228 35 19',
    website: "Ma'lumot mavjud emas",
    adminName: 'Dr. M.A. Matyoqubov',
    activeUsersCount: 20,
    totalPatientsCount: 1280,
    activeScreeningsCount: 138,
    status: 'ACTIVE',
    licenseExpiry: '2028-08-14',
    isTbSpecialized: true,
    services: ['GeneXpert MTB/RIF diagnostikasi', 'Rentgenografiya va flyuorografiya', 'DOTS ambulator xizmati', 'Reabilitatsiya'],
    lastVerifiedDate: '2026-08-09',
    verificationSource: 'Xorazm viloyati Sog‘liqni saqlash boshqarmasi',
    googleMapsQuery: 'Urganch sh., Xonqa ko‘chasi, 48',
  },
];
